"use client";
import { useEffect, useRef, useState, type PointerEvent } from 'react';
import { X, Volume2, VolumeX, ChevronDown, Play, Pause } from 'lucide-react';
import { useMotion } from './use-motion';

const ART='/assets/grace/';
const DATE='2027-01-20T18:00:00+04:00';
function Ornament(){return <img className="grace-ornament" src={`${ART}ornament.webp`} alt="" loading="lazy"/>}
function Flowers({className=''}:{className?:string}){return <img className={`grace-flowers ${className}`} src={`${ART}flowers.webp`} alt="" loading="lazy"/>}
function ScratchDate({value,label}:{value:string;label:string}){
 const canvas=useRef<HTMLCanvasElement>(null);const [revealed,setRevealed]=useState(false);const distance=useRef(0);const previous=useRef<{x:number;y:number}|null>(null);
 useEffect(()=>{const c=canvas.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;const gradient=ctx.createLinearGradient(0,0,220,260);gradient.addColorStop(0,'#fbf4df');gradient.addColorStop(.45,'#e6d3a3');gradient.addColorStop(1,'#b9904c');ctx.fillStyle=gradient;ctx.fillRect(0,0,220,260);ctx.strokeStyle='#ffffff45';ctx.lineWidth=2;for(let i=-260;i<260;i+=30){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i+260,260);ctx.stroke();}},[]);
 const scratch=(e:PointerEvent<HTMLCanvasElement>)=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const c=e.currentTarget;const r=c.getBoundingClientRect();const x=(e.clientX-r.left)*220/r.width,y=(e.clientY-r.top)*260/r.height;const ctx=c.getContext('2d');if(!ctx)return;ctx.globalCompositeOperation='destination-out';ctx.lineWidth=46;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(previous.current?.x??x,previous.current?.y??y);ctx.lineTo(x,y);ctx.stroke();if(previous.current)distance.current+=Math.hypot(x-previous.current.x,y-previous.current.y);previous.current={x,y};if(distance.current>700)setRevealed(true);};
 return <div className="grace-date-item"><div className={`grace-scratch ${revealed?'uncovered':''}`}><strong aria-hidden={!revealed}>{value}</strong>{!revealed&&<canvas ref={canvas} width={220} height={260} aria-hidden="true" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);previous.current=null;scratch(e);}} onPointerMove={scratch} onPointerUp={()=>{previous.current=null;}} onPointerCancel={()=>{previous.current=null;}}/>}<button className="scratch-access" onClick={()=>setRevealed(true)} aria-label={`Reveal ${label}`}>Reveal</button></div><span>{label}</span></div>
}
function Countdown(){const [remaining,setRemaining]=useState<number|null>(null);useEffect(()=>{const update=()=>setRemaining(Math.max(0,Date.parse(DATE)-Date.now()));update();const timer=setInterval(update,1000);return()=>clearInterval(timer);},[]);const s=Math.floor((remaining??0)/1000);return <div className="grace-countdown" aria-label="Countdown to the sample celebration">{[Math.floor(s/86400),Math.floor(s/3600)%24,Math.floor(s/60)%60,s%60].map((n,i)=><div key={i}><strong>{remaining===null?'—':String(n).padStart(2,'0')}</strong><span>{['Days','Hours','Minutes','Seconds'][i]}</span></div>)}</div>}

export default function GraceInvitation(){
 useMotion();
 const [opening,setOpening]=useState(false),[opened,setOpened]=useState(false),[music,setMusic]=useState(false),[playing,setPlaying]=useState(true),[modal,setModal]=useState<'rsvp'|'gifts'|null>(null),[sent,setSent]=useState(false),[attendance,setAttendance]=useState('yes'),[showMap,setShowMap]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),video=useRef<HTMLVideoElement>(null),audio=useRef<AudioContext|null>(null),musicTimer=useRef<ReturnType<typeof setInterval>|null>(null),openTimer=useRef<ReturnType<typeof setTimeout>|null>(null),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(!modal)return;dialog.current?.showModal();return()=>dialog.current?.close();},[modal]);
 useEffect(()=>()=>{if(openTimer.current)clearTimeout(openTimer.current);if(musicTimer.current)clearInterval(musicTimer.current);void audio.current?.close();},[]);
 const open=()=>{setOpening(true);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;openTimer.current=setTimeout(()=>{setOpened(true);setOpening(false);heading.current?.focus({preventScroll:true});if(!reduced)void video.current?.play().catch(()=>setPlaying(false));else setPlaying(false);},reduced?0:2800);};
 const toggleMusic=()=>{if(music){if(musicTimer.current)clearInterval(musicTimer.current);void audio.current?.suspend();setMusic(false);return;}const ctx=audio.current??new AudioContext();audio.current=ctx;void ctx.resume();let note=0;const notes=[261.63,329.63,392,523.25,392,329.63,293.66,349.23];const play=()=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=notes[note++%notes.length];gain.gain.setValueAtTime(0,ctx.currentTime);gain.gain.linearRampToValueAtTime(.065,ctx.currentTime+.08);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+1.6);osc.connect(gain);gain.connect(ctx.destination);osc.start();osc.stop(ctx.currentTime+1.7);};play();musicTimer.current=setInterval(play,700);setMusic(true);};
 return <main className={`grace-page ${opened?'grace-open':''}`}>
 <nav className="grace-toolbar" aria-label="Invitation preview"><a href="/designs">← Collection</a><span>EVERLASTING GRACE</span><a href="/create?design=everlasting-grace">Make it yours</a></nav>
 {!opened&&<div className={`grace-opening ${opening?'is-opening':''}`}><div className="grace-envelope"><div className="grace-envelope-half upper"/><div className="grace-envelope-half lower"/><button className="grace-seal" aria-label="Open Younuz and Amelia’s invitation" onClick={open} disabled={opening}><span>Y<span>&</span>A</span></button><span className="grace-tap">{opening?'YOUR INVITATION IS UNFOLDING':'TAP THE SEAL TO OPEN'}</span></div></div>}
 <div className="grace-content" inert={!opened}>
 <section className="grace-hero"><video ref={video} src={opened?`${ART}hero-mobile.mp4`:undefined} poster={`${ART}hero-poster.webp`} muted loop playsInline preload="none"/><div className="grace-hero-names"><p>THE WEDDING CELEBRATION OF</p><h1 ref={heading} tabIndex={-1}>Younuz <em>&</em> Amelia</h1><span>20 · 01 · 2027</span></div><a className="grace-scroll" href="#grace-date">Scroll down<ChevronDown size={22}/></a></section>
 <section className="grace-date" id="grace-date"><h2 data-reveal>The Date</h2><p>✦ Scratch to reveal the date ✦</p><div className="grace-date-row"><ScratchDate value="20" label="Day"/><ScratchDate value="01" label="Month"/><ScratchDate value="2027" label="Year"/></div><p className="grace-small">Swipe each card, or use its Reveal button.</p></section>
 <section className="grace-couple" data-reveal><div className="grace-arch-art"/><div className="grace-couple-copy"><p lang="ar" dir="rtl" className="grace-arabic">بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ</p><p className="grace-upper">YOU ARE INVITED TO THE<br/>NIKKAH CEREMONY OF</p><h2>Younuz</h2><Ornament/><p className="grace-family">TOGETHER WITH HIS FAMILY</p><span className="grace-with">With</span><h2>Amelia</h2><Ornament/><p className="grace-family">TOGETHER WITH HER FAMILY</p><h3>Dear Friends and Family</h3><p>Join us for an evening of love, laughter and duas as we celebrate the beginning of our forever.</p></div><Flowers className="left"/><Flowers className="right"/></section>
 <section className="grace-verse" data-reveal><Ornament/><p lang="ar" dir="rtl">وَخَلَقْنَاكُمْ أَزْوَاجًا</p><p>“And We created you in pairs.”<br/>(Surah An-Naba 78:8)</p></section>
 <section className="grace-timeline"><h2 data-reveal>Wedding Timeline</h2><Ornament/><div className="grace-timeline-line">{[['18:00','Guest arrival','Welcome drinks & warm embraces','arrival'],['18:30','Bride entrance','A beautiful beginning','prayer'],['19:30','Salat al Isha','A moment for prayer','bride'],['20:30','Dinner is served','Gather around the table','dinner'],['22:00','Let the fun begin','An evening to remember','celebration']].map(([time,title,copy,art],i)=><article className={i%2?'reverse':''} data-reveal key={time}><img src={`${ART}${art}.webp`} alt="" loading="lazy"/><div><span>{time}</span><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
 <section className="grace-celebration" data-reveal><h2>The Celebration Begins</h2><Ornament/><Countdown/></section>
 <section className="grace-location" data-reveal><Flowers/><h2>Location</h2><Ornament/><h3>DUBAI</h3><p>Four Seasons Resort Dubai at Jumeirah Beach<br/>Sample celebration venue</p><img className="grace-venue" src={`${ART}venue.webp`} alt="Illustrative palatial wedding venue with palm trees" loading="lazy"/><div className="grace-map">{showMap?<iframe title="Map of the sample Dubai wedding venue" src="https://maps.google.com/maps?q=Four%20Seasons%20Resort%20Dubai%20at%20Jumeirah%20Beach&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/>:<button onClick={()=>setShowMap(true)} className="grace-button">Show venue map</button>}</div><a className="grace-button" href="https://www.google.com/maps/search/?api=1&query=Four+Seasons+Resort+Dubai+at+Jumeirah+Beach" target="_blank" rel="noreferrer">Open location in Maps ↗</a></section>
 <section className="grace-dress" data-reveal><h2>Dress Code</h2><Ornament/><img src={`${ART}attire.webp`} alt="Traditional formal attire in soft pastel shades" loading="lazy"/><p>We invite you to wear</p><h3>Traditional Pakistani Attire</h3><p>in soft pastel shades.</p><p>Recommended shades</p><div className="grace-swatches" aria-label="Pastel pink, blue, lilac and peach"><i/><i/><i/><i/></div><Ornament/><p>Please reserve ivory and beige for the couple.<br/>Sage green is reserved for the bridesmaids.</p></section>
 <section className="grace-gift" data-reveal><Flowers className="left"/><h2>Gift Preferences</h2><Ornament/><p>Your presence and prayers are the most meaningful gift. If you would like to give a little something, explore our sample gift preferences.</p><button className="grace-button" onClick={()=>setModal('gifts')}>View gift preferences</button><Ornament/><p>We look forward to an adults-only celebration.<br/>Thank you for your understanding.</p><Flowers className="right"/></section>
 <section className="grace-rsvp" data-reveal><h2>Confirm Your Attendance</h2><Ornament/><p>Please let us know whether you can join us<br/>by 30 November 2026.</p><button className="grace-button" onClick={()=>{setSent(false);setModal('rsvp');}}>RSVP</button><p className="grace-small">Sample invitation · responses are not sent.</p></section>
 <section className="grace-signoff"><Flowers className="left"/><h2>Hope to see you there</h2><p>With love,</p><h3>Younuz & Amelia</h3><a href="/" aria-label="AlwaysEverafter home"><img src="/assets/wordmark.webp" alt="Always Ever After"/></a><span>Designed with love</span><Flowers className="right"/></section>
 </div>
 {opened&&<div className="grace-controls"><button onClick={toggleMusic} aria-label={music?'Pause music':'Play music'}>{music?<Volume2 size={19}/>:<VolumeX size={19}/>}</button><button onClick={()=>{if(playing)video.current?.pause();else void video.current?.play().catch(()=>{});setPlaying(!playing);}} aria-label={playing?'Pause background video':'Play background video'}>{playing?<Pause size={17}/>:<Play size={17}/>}</button></div>}
 {modal&&<dialog ref={dialog} className="grace-dialog" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null);}} aria-labelledby="grace-dialog-title"><button className="grace-close" onClick={()=>setModal(null)} aria-label="Close dialog"><X/></button><h2 id="grace-dialog-title">{modal==='gifts'?'A thoughtful gesture':'Confirm your attendance'}</h2>{modal==='gifts'?<><p>Your company is our favourite gift.</p><p>This is a demonstration. A personalised invitation can link to your own gift registry or share your preferred charity.</p><button className="grace-button" onClick={()=>setModal(null)}>Lovely, thank you</button></>:sent?<div role="status"><h3>{attendance==='yes'?'We look forward to celebrating!':'Thank you for letting us know.'}</h3><p>Your sample response was recorded for this preview only. Nothing has been sent or saved.</p><button className="grace-button" onClick={()=>setModal(null)}>Close</button></div>:<form onSubmit={e=>{e.preventDefault();setSent(true);}}><p>Please RSVP by 30 November 2026.</p><label>Your full name<input name="name" autoComplete="name" required maxLength={120}/></label><fieldset><legend>Will you be joining us?</legend><label><input type="radio" name="attendance" value="yes" checked={attendance==='yes'} onChange={()=>setAttendance('yes')}/> Joyfully accepts</label><label><input type="radio" name="attendance" value="no" checked={attendance==='no'} onChange={()=>setAttendance('no')}/> Regretfully declines</label></fieldset>{attendance==='yes'&&<label>Number of guests<input type="number" name="guests" required min="1" max="10" defaultValue="1"/></label>}<button className="grace-button">Submit sample RSVP</button><p className="grace-small">Demo only. No response is sent to the couple.</p></form>}</dialog>}
 </main>
}
